blank_issues_enabled: false
contact_links:
  - name: Documentación del proyecto
    url: https://auditoria-frontend-gw7wwpskbq-tl.a.run.app
    about: Consultá la documentación antes de abrir un issue.
